apiVersion: v2
name: my-app
description: A Helm chart for deploying a Vue + Spring + SQL database application
version: 0.1.0
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: database
    version: 0.1.0
    repository: "file://charts/database"
