apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      containers:
        - name: database
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysqlRootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase }}
            - name: MYSQL_USER
              value: {{ .Values.mysqlUser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
